name: Cypress Tests

on:
  pull_request:
    branches:
      - main
      - develop
      - qa
  workflow_dispatch:  

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Create Env Variables
        run: |
          echo 'CYPRESS_api_key_dcs=${{ secrets.CYPRESS_API_KEY_DCS }}' >> .env
          echo 'CYPRESS_api_key_cloud=${{ secrets.CYPRESS_API_KEY_CLOUD }}' >> .env
          echo 'CYPRESS_endpoint_cloud_url=${{ secrets.CYPRESS_CLOUD_URL }}' >> .env

      - name: Run Cypress tests
        run: npx cypress run

      - name: Upload Fail Screenshots
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload Videos Of Execution
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: cypress/videos
